# Site settings
title: Don Giovanni collations
email: lxpugin@gmail.com
baseurl: "" 

# Build settings
markdown: kramdown

top_menu:
    - id: home
      url: "index.html"
      text: Home
    - id: samples
      url: "samples.html"
      text: Samples
    - id: description
      url: "description.html"
      text: Description
    - id: nowhere
      url: "broken.html"
      text: Try it
